
app:
  version: 1
  info: "Testing app"
  message: "Hello from the YAML configuration!"
  port: "${server.port:7070}"

  keycloak:
    base-url: ${KEYCLOAK_BASE_URL:http://localhost:9090}
    realm: ${KEYCLOAK_REALM:ite}
    admin-realm: ${KEYCLOAK_ADMIN_REALM:master}
    admin-client-id: ${KEYCLOAK_ADMIN_CLIENT_ID:admin-cli}
    admin-username: ${KEYCLOAK_ADMIN_USERNAME:temp-admin}
    admin-password: ${KEYCLOAK_ADMIN_PASSWORD:iam@123}

server:
  port: 7070

file:
  client-path: /file
  storage-location: /Users/thornie/Desktop/FilesServer/
  base-uri: http://localhost:7070${file.client-path}

minio:
  endpoint: ${MINIO_ENDPOINT:https://storage.chanthorndev.site}
  access-key: admin
  secret-key: qwerqwer
  bucket-name: ite-bucket

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  endpoint:
    health:
      show-details: always
spring:
  config:
    import: optional:file:.env[.properties],optional:file:../.env[.properties],optional:file:ecommerce/.env[.properties]

  application:
    name: ecommerce

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 50MB

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:9090/realms/ite}
          #jwk-set-uri: ${KEYCLOAK_JWK_SET_URI:http://localhost:9090/realms/ite/protocol/openid-connect/certs}
          #issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:9090/realms/ite}
          #jwk-set-uri: ${KEYCLOAK_JWK_SET_URI:http://localhost:9090/realms/ite/protocol/openid-connect/certs}

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5850/ite}
    username: admin
    password: admin@123
    driver-class-name: org.postgresql.Driver

  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: update
    show-sql: false

  threads:
    virtual:
      enabled: true

cloudflare:
  r2:
    image-folder: ${CLOUDFLARE_R2_IMAGE_FOLDER:images}
    max-image-size: ${CLOUDFLARE_R2_MAX_IMAGE_SIZE:5242880}
    access-key: ${CLOUDFLARE_R2_ACCESS_KEY}
    secret-key: ${CLOUDFLARE_R2_SECRET_KEY}
    endpoint: ${CLOUDFLARE_R2_ENDPOINT}
    public-url: ${CLOUDFLARE_R2_PUBLIC_URL}
    bucket-name: ${CLOUDFLARE_R2_BUCKET_NAME}

bakong:
  account-id: ${BAKONG_ACCOUNT_ID:}
  base-url: ${BAKONG_BASE_URL:https://api-bakong.nbc.gov.kh}
  api-token: ${BAKONG_API_TOKEN:}
  email: ${BAKONG_EMAIL:${EMAIL:}}

ecommerce:
  payment:
    currency: ${ECOMMERCE_PAYMENT_CURRENCY:USD}
