
plugins {
    id 'org.springframework.boot'
    id 'io.spring.dependency-management'
}

dependencies {

    implementation project(':common')

    implementation 'org.springframework.boot:spring-boot-starter-webmvc'

    // Bakong KHQR SDK
    implementation 'kh.gov.nbc.bakong_khqr:sdk-java:1.0.0.16'

    // QR code image generation (ZXing)
    implementation 'com.google.zxing:core:3.5.3'
    implementation 'com.google.zxing:javase:3.5.3'

    // Validation
    implementation 'org.springframework.boot:spring-boot-starter-validation'

    // JSON parsing
    implementation 'com.fasterxml.jackson.core:jackson-databind'

    testImplementation 'org.springframework.boot:spring-boot-starter-test'

    //testRuntimeOnly 'org.junit.platform:junit-platform-launcher'

    // Lombok
    compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'
    testCompileOnly 'org.projectlombok:lombok'
    testAnnotationProcessor 'org.projectlombok:lombok'

}
